spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
      url: jdbc:mysql://39.106.50.191:3306/excel?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Mysql8_root
      hikari:
        minimum-idle: 5
        maximum-pool-size: 10
        auto-commit: true
        idle-timeout: 30000
        pool-name: excel
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: select 1


